### ISSUE TITLE
Update code as per assignment.

### ISSUE THREAD

**Issue by MorganTDicks** [Austin-ALIT/Eve-React-Intro#1]
I have added some comment to the code for improvements but otherwise looks good. :)

[ProductList](https://github.com/Austin-ALIT/Eve-React-Intro/commit/dd6de047bc4fb2ee07fbd7b8d168dd1df7e13628#r118732512)

[Product](https://github.com/Austin-ALIT/Eve-React-Intro/commit/dd6de047bc4fb2ee07fbd7b8d168dd1df7e13628#r118732627)

**Comment by Austin-ALIT** [comment]
I have made the changes in commits 2 ([ProductList](https://github.com/Austin-ALIT/Eve-React-Intro/commit/7dc7eee35fb7a9964fdd79b93ad8e2cd81c2805c#diff-5f37122736428c6a7d5b275ec69688bf3bc04b2450355ffb81214836d8b5e3eb)) & 3 ([Product](https://github.com/Austin-ALIT/Eve-React-Intro/commit/cfb65c0c28e76ccdc4a387e11c38b9231af7af0a#diff-7aa9432bb7702e518e485c8abc57e76d17141d14a30962d465845df0726e6065)).
